apiVersion: v1
kind: Service
metadata:
  name: sometestapi-server
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
  selector:
    app.kubernetes.io/name: sometestapi-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sometestapi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sometestapi-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sometestapi-server
    spec:
      containers:
        - name: sometestapi-server
          image: aimalkhan26/sometesapi
          ports:
            - containerPort: 3000